In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf
# Keras
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Dense
from tensorflow.keras.datasets import mnist
# Sklearn scaling
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from PIL import Image
import time

In [2]:
# cols = ['fileName', 'imageData','fruitName']
cols = ['fileName', 'fruitName']
# X = np.empty([67692, 30000], dtype = int)
X = []
masterdf = pd.DataFrame(columns=cols)


In [3]:
def jpeg_convert(file_name):
    with Image.open(file_name) as img:
        array = np.array(img).reshape(30000)
        return array

In [4]:
time_start = time.perf_counter()
parentDirectory = os.path.join('data', 'fruits-360','Training')
i=0

for subdir, dirs, files in os.walk(parentDirectory):
    for file in files:
        fileName= file[:-4]
        subdirName = subdir[5:]
        imagePath = os.path.join(subdir,file)
        X.append(jpeg_convert(imagePath))
#         X[i,:] = (jpeg_convert(imagePath))
#         imageData = jpeg_convert(imagePath)
#         masterdf.loc[i] = [fileName, imageData, subdirName]
        masterdf.loc[i] = [fileName, subdirName]
        i+=1
        if i%1000 == 0:
            print(i)

time_stop = time.perf_counter()
print(f"Total elapsed time is {time_stop-time_start:0.4f} seconds")
masterdf

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
Total elapsed time is 389.2915 seconds


fileName                           fruitName
0         0_100  fruits-360\Training\Apple Braeburn
1       100_100  fruits-360\Training\Apple Braeburn
2       101_100  fruits-360\Training\Apple Braeburn
3       102_100  fruits-360\Training\Apple Braeburn
4       103_100  fruits-360\Training\Apple Braeburn
...         ...                                 ...
67687   r_6_100      fruits-360\Training\Watermelon
67688   r_7_100      fruits-360\Training\Watermelon
67689  r_81_100      fruits-360\Training\Watermelon
67690   r_8_100      fruits-360\Training\Watermelon
67691   r_9_100      fruits-360\Training\Watermelon

[67692 rows x 2 columns]

In [5]:
X = np.array(X)
X.shape

(67692, 30000)

In [6]:
# X = masterdf[['imageData']]
y = masterdf[['fruitName']]
y

fruitName
0      fruits-360\Training\Apple Braeburn
1      fruits-360\Training\Apple Braeburn
2      fruits-360\Training\Apple Braeburn
3      fruits-360\Training\Apple Braeburn
4      fruits-360\Training\Apple Braeburn
...                                   ...
67687      fruits-360\Training\Watermelon
67688      fruits-360\Training\Watermelon
67689      fruits-360\Training\Watermelon
67690      fruits-360\Training\Watermelon
67691      fruits-360\Training\Watermelon

[67692 rows x 1 columns]

# One Hot Encoding

In [7]:
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

one_hot_y = to_categorical(encoded_y)
one_hot_y

C:\Users\Gabriel\Anaconda3\envs\PythonAdv\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [8]:
time_start = time.perf_counter()
X_scaler = MinMaxScaler().fit(X)
X_train_scaled = X_scaler.transform(X)
time_stop = time.perf_counter()
print(f"Total elapsed time is {time_stop-time_start:0.4f} seconds")
X_train_scaled

Total elapsed time is 368.0702 seconds


array([[0.99130435, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99130435, 1.        , 0.95294118, ..., 1.        , 1.        ,
        1.        ],
       [0.9826087 , 1.        , 0.94117647, ..., 1.        , 1.        ,
        1.        ],
       ...,
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

In [9]:
X_train_scaled.shape

(67692, 30000)

In [28]:
model = Sequential()

In [29]:
model.add(Dense(200, activation='relu', input_dim=30000))

In [30]:
model.add(Dense(200, activation='relu'))

In [31]:
model.add(Dense(200, activation='relu'))

In [32]:
model.add(Dense(131, activation='softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_9 (Dense)              (None, 200)               6000200   
_________________________________________________________________
dense_10 (Dense)             (None, 200)               40200     
_________________________________________________________________
dense_11 (Dense)             (None, 200)               40200     
_________________________________________________________________
dense_12 (Dense)             (None, 131)               26331     
Total params: 6,106,931
Trainable params: 6,106,931
Non-trainable params: 0
_________________________________________________________________


In [33]:
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [34]:
# Fit (train) the model
model.fit(
    X_train_scaled,
    one_hot_y,
    epochs=10,
    shuffle=True,
    verbose=2
)

Train on 67692 samples
Epoch 1/10
67692/67692 - 75s - loss: 0.9331 - accuracy: 0.7456
Epoch 2/10
67692/67692 - 69s - loss: 0.2258 - accuracy: 0.9277
Epoch 3/10
67692/67692 - 71s - loss: 0.1862 - accuracy: 0.9426
Epoch 4/10
67692/67692 - 74s - loss: 0.1493 - accuracy: 0.9555
Epoch 5/10
67692/67692 - 74s - loss: 0.1447 - accuracy: 0.9592
Epoch 6/10
67692/67692 - 69s - loss: 0.1212 - accuracy: 0.9656
Epoch 7/10
67692/67692 - 67s - loss: 0.1274 - accuracy: 0.9659
Epoch 8/10
67692/67692 - 78s - loss: 0.1187 - accuracy: 0.9701
Epoch 9/10
67692/67692 - 78s - loss: 0.1153 - accuracy: 0.9715
Epoch 10/10
67692/67692 - 77s - loss: 0.1029 - accuracy: 0.9766


In [35]:
time_start = time.perf_counter()
parentDirectory = os.path.join('data', 'fruits-360','Test')
X_test = []
testdf = pd.DataFrame(columns=cols)
i=0

for subdir, dirs, files in os.walk(parentDirectory):
    for file in files:
        fileName= file[:-4]
        subdirName = subdir[5:]
        imagePath = os.path.join(subdir,file)
        X_test.append(jpeg_convert(imagePath))
#         X[i,:] = (jpeg_convert(imagePath))
#         imageData = jpeg_convert(imagePath)
#         masterdf.loc[i] = [fileName, imageData, subdirName]
        testdf.loc[i] = [fileName, subdirName]
        i+=1
        if i%1000 == 0:
            print(i)

time_stop = time.perf_counter()
print(f"Total elapsed time is {time_stop-time_start:0.4f} seconds")
testdf

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
Total elapsed time is 110.5683 seconds


fileName                       fruitName
0       321_100  fruits-360\Test\Apple Braeburn
1       322_100  fruits-360\Test\Apple Braeburn
2       323_100  fruits-360\Test\Apple Braeburn
3       324_100  fruits-360\Test\Apple Braeburn
4       325_100  fruits-360\Test\Apple Braeburn
...         ...                             ...
22683  r_95_100      fruits-360\Test\Watermelon
22684  r_96_100      fruits-360\Test\Watermelon
22685  r_97_100      fruits-360\Test\Watermelon
22686  r_98_100      fruits-360\Test\Watermelon
22687  r_99_100      fruits-360\Test\Watermelon

[22688 rows x 2 columns]

In [37]:
X_test = np.array(X_test)
time_start = time.perf_counter()
X_test_scaled = X_scaler.transform(X_test)
time_stop = time.perf_counter()
print(f"Total elapsed time is {time_stop-time_start:0.4f} seconds")
X_test_scaled

Total elapsed time is 8.1962 seconds


array([[1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       ...,
       [0.99130435, 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ],
       [0.99130435, 1.        , 0.97647059, ..., 1.        , 1.        ,
        1.        ],
       [1.        , 1.        , 1.        , ..., 1.        , 1.        ,
        1.        ]])

In [60]:
img = X_test_scaled[22260,:].reshape(-1, 30000)

In [61]:
model.predict(img).round()

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0.]], dtype=float32)

In [55]:
one_hot_y

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)